# Generated by Django 5.0.4 on 2024-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
